[package]
name = "picvu"
version = "0.1.0"
authors = ["kezenator <github@kezenator.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
picvudb = { path = "../picvudb" }
actix="0.9.0"
actix-rt="1.1.1"
actix-web="2.0.0"
horrorshow="0.8.3"
